### ISSUE TITLE
Empty Page

### ISSUE THREAD

**Issue by Nicicalu** [littlegolden/syntax-highlight-word#1]
Hey littlegoden

Thanks for publishing this code.
When running the server I get an empty page. This only happens when I try to run it in Prod (on 0.0.0.0 instead of localhost)

Can you run this code in prod without problems? If yes, how?

**Comment by littlegolden** [comment]
> Hey littlegoden
> 
> Thanks for publishing this code.
> When running the server I get an empty page. This only happens when I try to run it in Prod (on 0.0.0.0 instead of localhost)
> 
> Can you run this code in prod without problems? If yes, how?

hi, what is Prod? it it a cloud server product?

**Comment by Nicicalu** [comment]
> > Hey littlegoden
> > Thanks for publishing this code.
> > When running the server I get an empty page. This only happens when I try to run it in Prod (on 0.0.0.0 instead of localhost)
> > Can you run this code in prod without problems? If yes, how?
> 
> hi, what is Prod? it it a cloud server product?

Sorry, I meant production^^

**Comment by Nicicalu** [comment]
It works when using `npm run dev`, but that only listens to localhost:8080, I want to access it from a different device. Sorry I'm new to Nodejs

**Comment by littlegolden** [comment]
you dont need change any thing in file `webpack.*.confg`, Ip Change section is here https://github.com/littlegolden/syntax-highlight-word/blob/401b78a874198c0cff9d18ef0c918757ebe21198/config/index.js#L16-L17

**Comment by littlegolden** [comment]
if you need to serve different host and port in different environment, your edit to `package.json` is right, all you need to do is delete these changes as blow in `webpack.dev.conf.js` and `webpack.prod.conf.js`:

```
  target: 'web',
   entry: [
    'webpack-dev-server/client?http://0.0.0.0:8080'
   ],
```

**Comment by Nicicalu** [comment]
> you dont need change any thing in file `webpack.*.confg`, Ip Change section is here
> 
> https://github.com/littlegolden/syntax-highlight-word/blob/401b78a874198c0cff9d18ef0c918757ebe21198/config/index.js#L16-L17

It worked this way. Thanks mate. I had to add `--disable-host-check` to the `webpack-dev-server` command in the `package.json` though.

**Comment by Nicicalu** [comment]
I forked your repo and added a Dockerfile. Feel free to copy it for your repo. I used docker for my own environment.
https://github.com/Nicicalu/syntax-highlight-word-1/

**Comment by littlegolden** [comment]
> It worked this way. Thanks mate. I had to add --disable-host-check to the webpack-dev-servercommand in the package.json though.

good to hear~

> I forked your repo and added a Dockerfile. Feel free to copy it for your repo. I used docker for my own environment.
> https://github.com/Nicicalu/syntax-highlight-word-1/

thank you, that's so generous. 🥰

**Comment by Nicicalu** [comment]
Thank you! This really helped me :-)
